name: firestore_helper_methods
description: These helpers wil help out significantly.  Base Firestore methods are available. See the example for implementation.

version: 1.0.1
repository: https://github.com/godfreycomputing/firestore_helper_methods
issues: https://github.com/godfreycomputing/firestore_helper_methods/issues

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
dependencies: 
  cloud_firestore: ^3.1.8
  equatable: ^2.0.3
  firebase_core: ^1.12.0
  
